/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol CKTranscriptComposeDelegate <NSObject>
-(BOOL)supportsAttachments;
-(void)showNewMessageCompositionForMessageParts:(id)messageParts;
-(void)showForwardedMessageParts:(id)parts;
-(void)transcriptController:(id)controller didSendMessageInConversation:(id)conversation;
-(void)transcriptController:(id)controller willSendComposition:(id)composition inConversation:(id)conversation;
-(void)didCancelComposition:(id)composition;
@optional
-(BOOL)canEditRecipients;
@end

