/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIApplication.h>
#import "CNFRegWizardControllerDelegate.h"
#import "IMSystemMonitorListener.h"
#import "UIApplicationDelegate.h"
#import "MobileSMS-Structs.h"

@class CKMessagesController, CNFRegWizardController, NSString, NSURL, FTCAccountMonitor, FTCConnectionHandler, BKSProcessAssertion, TLAlert, UIWindow;

__attribute__((visibility("hidden")))
@interface SMSApplication : UIApplication <CNFRegWizardControllerDelegate, IMSystemMonitorListener, UIApplicationDelegate> {
	BOOL _waitToSendFinishLaunching;
	BOOL _isLocked;
	BOOL _isSuspended;
	BOOL _hasEmail;
	UIWindow* _window;
	CKMessagesController* _messagesController;
	int _delaySuspendCount;
	unsigned _backgroundTask;
	CNFRegWizardController* _madridRegistrationController;
	NSString* _defaultPng;
	int _suspendTimeStatusBarStyle;
	NSURL* _deferredLoadURL;
	FTCAccountMonitor* _accountMonitor;
	FTCConnectionHandler* _connectionHandler;
	BKSProcessAssertion* _backgroundAssertion;
	TLAlert* _alert;
}
@property(retain, nonatomic) UIWindow* window;
@property(retain, nonatomic) NSURL* deferredLoadURL;
-(void)_handleDaemonDisconnected:(id)disconnected;
-(void)_handleDaemonConnected:(id)connected;
-(void)_handleAccountsChanged:(id)changed;
-(BOOL)_shouldShowMadridRegistrationView;
-(void)firstRunControllerDidFinish:(id)firstRunController finished:(BOOL)finished;
-(void)_updateMadridRegistrationViewAnimated:(BOOL)animated;
-(void)_destroyMadridRegistrationView;
-(void)_createMadridRegistrationViewIfNecessary;
-(void)_showMadridRegistrationViewIfNecessary;
-(void)__showMadridRegistrationViewIfNecessary;
-(BOOL)_shouldUseKeyWindowStack;
-(void)_updateDefaultPNGSuspended:(id)suspended;
-(id)_defaultPNGOverrideSuspended;
-(id)_defaultPNGOverrideInitial;
-(BOOL)_isShowingNewComposition;
-(void)applicationDidEndResumeAnimation;
-(void)significantTimeChange;
-(BOOL)applicationSuspend:(GSEventRef)suspend settings:(id)settings;
-(void)systemApplicationDidResumeForEventsOnly;
-(void)systemApplicationDidSuspendForEventsOnly;
-(void)systemApplicationDidResume;
-(void)systemApplicationDidSuspend;
-(void)applicationDidBecomeActive:(id)application;
-(void)applicationDidResumeFromUnderLock;
-(void)_prepareForResume:(BOOL)resume;
-(void)_prepareForSuspend;
-(BOOL)openURL:(id)url;
-(void)reportAppLaunchFinished;
-(void)setWaitToSendFinishLaunching:(BOOL)sendFinishLaunching;
-(void)applicationOpenURL:(id)url;
-(BOOL)isLocked;
-(BOOL)isHandlingURL;
-(void)_storeState;
-(BOOL)_restoreState;
-(void)_migrateLegacySettingsIfNecessary;
-(void)handleURL:(id)url;
-(void)_receivedMessage:(id)message;
-(void)_resetIdleTimer;
-(void)_playMessageReceivedForMessage:(id)message;
-(void)stopPlayingLastAlertTone;
-(void)_updateNetworkFlags;
-(void)dealloc;
-(BOOL)application:(id)application didFinishLaunchingWithOptions:(id)options;
-(id)init;
-(id)defaultPng;
-(void)setDefaultPng:(id)png;
-(void)_clearFailureBadge;
-(void)_mediaDidFinishSaving;
-(void)_mediaDidStartSaving;
-(void)didChangeOrientation:(id)orientation;
-(void)startScrollConversationsTest:(id)test;
-(void)startRotationTest:(id)test;
-(void)startScrollTranscriptTest:(id)test;
-(void)startShowMessagesTest:(id)test;
-(void)showNextMessage;
-(void)didShowTranscriptList;
-(void)didShowAMessage;
-(void)scrollTranscript;
-(void)showTranscriptListNotAnimated;
-(void)showTranscriptList;
-(void)failedTest:(id)test;
-(void)finishedTest:(id)test extraResults:(id)results;
-(BOOL)runTest:(id)test options:(id)options;
@end

